local dapui = require("dapui")
local dap = require("dap")
dapui.setup()
require("nvim-dap-virtual-text").setup()

vim.keymap.set('n', '<leader>dco', function() dap.continue() end)
vim.keymap.set('n', '<leader>dso', function() dap.step_over() end)
vim.keymap.set('n', '<leader>dsi', function() dap.step_into() end)
vim.keymap.set('n', '<leader>dst', function() dap.step_out() end)
vim.keymap.set('n', '<Leader>db', function()  dap.toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>dB', function()  dap.set_breakpoint() end)
vim.keymap.set('n', '<Leader>dl', function()  dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end)
vim.keymap.set('n', '<Leader>dr', function()  dap.repl.open() end)
vim.keymap.set('n', '<Leader>dl', function()  dap.run_last() end)

vim.keymap.set({'n', 'v'}, '<Leader>de', function()
    dapui.eval()
end)

local widgets = require('dap.ui.widgets')
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
    widgets.hover()
end)
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
    widgets.preview()
end)
vim.keymap.set('n', '<Leader>df', function()
    widgets.centered_float(widgets.frames)
end)
vim.keymap.set('n', '<Leader>dsc', function()
    widgets.centered_float(widgets.scopes)
end)

local nvdap = require("dap")
nvdap.listeners.after.event_initialized["dapui_config"] = function()
    dapui.close()
    dapui.open()
end
vim.keymap.set('n', '<Leader>dcl', function() dapui.close() end)
vim.keymap.set('n', '<Leader>dd', function() dapui.open() end)
